language: objective-c
before_install:
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update
script:
    - bundle install
    - bundle exec rake pod:install > pod_log.txt
    - bundle exec rake clean
    - rm -rf sparkle
    - rm -f resources/dsa_pub.pem
    - bundle exec rake sparkle:setup_certificates
    - bundle exec rake spec
